[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Application")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Utils.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Form")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Form.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.ControlsContainer")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(
    "CrossSharp.Ui.ControlsContainer.Linux"
)]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.FormTitleBar")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.FormTitleBar.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Label")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Label.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Panel")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Panel.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Button")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.Button.Linux")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.CenterPanel")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("CrossSharp.Ui.CenterPanel.Linux")]
